// Bloub mascot engine — C# port.
// Original TypeScript: Bloub by Jérémy Perret (jeremy-prt), https://github.com/jeremy-prt/bloub
// Copyright (c) 2026 Jérémy Perret. Licensed under the MIT License (full text in BloubEngine.cs).
// Port of src/bot/shape.ts and src/bot/profiles.ts.

using System.Numerics;
using static Island.Lab.Mascot.BloubMath;

namespace Island.Lab.Mascot;

/// <summary>A 2D point in double precision (engine-internal; the frame exposes floats).</summary>
public readonly record struct PointD(double X, double Y);

/// <summary>
/// A silhouette = a radial profile r(theta) plus a pose.
///
/// Every shape is sampled at the SAME angles, so any two shapes have points that
/// correspond one to one and morphing reduces to a linear interpolation of radii.
/// That is what makes transitions clean without a path-morphing library.
/// </summary>
public sealed record Silhouette
{
    public required double[] Radii { get; init; }
    /// <summary>Profile rotation, radians.</summary>
    public double Rot { get; init; }
    /// <summary>Centre offset, in ball-radius units.</summary>
    public double Cx { get; init; }
    public double Cy { get; init; }
    /// <summary>Squash and stretch, applied in screen space (after rotation).</summary>
    public double Sx { get; init; } = 1;
    public double Sy { get; init; } = 1;
}

/// <summary>Radial profiles measured off the reference video (profiles.ts).</summary>
public enum ProfileName { Egg, Hexagon, Triangle }

/// <summary>Silhouette helpers (shape.ts).</summary>
public static class BloubShape
{
    /// <summary>Number of angular samples shared by every profile.</summary>
    public const int ProfileSamples = 64;

    // Radial profiles r(theta) measured to the pixel on the reference video.
    // theta = 0 points right and grows clockwise (y down). Unit: resting ball radius = 1.
    // Generated by tools/extract-profiles.py in the original project — do not edit by hand.

    /// <summary>Egg: same height as the ball, narrower. Measured footprint 1.647 x 2.000.</summary>
    static readonly double[] EggProfile = [0.8369,0.8424,0.8497,0.8585,0.8674,0.8775,0.8878,0.8983,0.9089,0.9185,0.9288,0.9374,0.9445,0.9504,0.9543,0.9559,0.9555,0.9519,0.9466,0.9389,0.9302,0.9193,0.9085,0.8969,0.8852,0.8734,0.8625,0.8513,0.8411,0.8325,0.8243,0.8179,0.8137,0.8112,0.8102,0.8128,0.8178,0.8262,0.8374,0.8518,0.8702,0.8922,0.9169,0.9446,0.9741,1.0023,1.0267,1.0433,1.0481,1.0393,1.0216,0.9970,0.9697,0.9418,0.9169,0.8949,0.8760,0.8604,0.8490,0.8394,0.8337,0.8314,0.8305,0.8326];
    /// <summary>Hexagon, point up, very rounded corners. Measured footprint 1.826 x 2.011.</summary>
    static readonly double[] HexagonProfile = [0.9210,0.9282,0.9441,0.9706,0.9984,1.0059,0.9896,0.9562,0.9290,0.9124,0.9047,0.9058,0.9157,0.9349,0.9642,0.9873,0.9882,0.9665,0.9336,0.9105,0.8968,0.8918,0.8955,0.9080,0.9293,0.9611,0.9820,0.9812,0.9590,0.9282,0.9089,0.8978,0.8964,0.9026,0.9189,0.9439,0.9778,0.9990,0.9964,0.9713,0.9439,0.9274,0.9196,0.9206,0.9308,0.9502,0.9799,1.0121,1.0226,1.0071,0.9752,0.9510,0.9366,0.9316,0.9351,0.9485,0.9711,1.0026,1.0213,1.0155,0.9863,0.9547,0.9347,0.9232];
    /// <summary>Triangle, point up, very rounded corners. Measured footprint 1.995 x 1.884.</summary>
    static readonly double[] TriangleProfile = [0.7819,0.8211,0.8747,0.9440,1.0223,1.0960,1.1401,1.1340,1.0808,1.0047,0.9265,0.8603,0.8104,0.7730,0.7450,0.7273,0.7151,0.7118,0.7148,0.7245,0.7427,0.7680,0.8037,0.8518,0.9148,0.9876,1.0583,1.1073,1.1109,1.0667,0.9940,0.9164,0.8482,0.7948,0.7555,0.7261,0.7056,0.6925,0.6859,0.6869,0.6938,0.7084,0.7305,0.7615,0.8040,0.8595,0.9311,1.0092,1.0791,1.1171,1.1054,1.0501,0.9779,0.9050,0.8450,0.7990,0.7656,0.7413,0.7258,0.7160,0.7146,0.7204,0.7330,0.7528];

    public static double[] Profile(ProfileName name) => name switch
    {
        ProfileName.Egg => EggProfile,
        ProfileName.Hexagon => HexagonProfile,
        _ => TriangleProfile,
    };

    internal static readonly double[] Angles = Enumerable.Range(0, ProfileSamples).Select(i => (double)i / ProfileSamples * Tau).ToArray();
    internal static readonly double[] Cos = Angles.Select(Math.Cos).ToArray();
    internal static readonly double[] Sin = Angles.Select(Math.Sin).ToArray();

    public static Silhouette FromProfile(ProfileName name) => new() { Radii = (double[])Profile(name).Clone() };

    /// <summary>Perfect circle: the neutral base (dot, bubble, fade target).</summary>
    public static Silhouette Circle(double radius) => new() { Radii = Filled(radius) };

    internal static double[] Filled(double v)
    {
        var a = new double[ProfileSamples];
        Array.Fill(a, v);
        return a;
    }

    /// <summary>Interpolates two silhouettes.</summary>
    public static Silhouette Blend(Silhouette a, Silhouette b, double t)
    {
        var radii = new double[ProfileSamples];
        for (int i = 0; i < ProfileSamples; i++)
            radii[i] = Lerp(At(a.Radii, i, 1), At(b.Radii, i, 1), t);
        // Rotation along the shortest path: avoids a full turn when going e.g. from +170deg to -170deg.
        double dRot = b.Rot - a.Rot;
        while (dRot > Math.PI) dRot -= Tau;
        while (dRot < -Math.PI) dRot += Tau;
        return new Silhouette
        {
            Radii = radii,
            Rot = a.Rot + dRot * t,
            Cx = Lerp(a.Cx, b.Cx, t),
            Cy = Lerp(a.Cy, b.Cy, t),
            Sx = Lerp(a.Sx, b.Sx, t),
            Sy = Lerp(a.Sy, b.Sy, t),
        };
    }

    static double At(double[] arr, int i, double fallback) => i < arr.Length ? arr[i] : fallback;

    /// <summary>Projects the silhouette to screen points. <paramref name="scale"/> = ball radius in viewBox units.</summary>
    public static PointD[] ToPoints(Silhouette s, double scale)
    {
        var outPts = new PointD[ProfileSamples];
        double cr = Math.Cos(s.Rot), sr = Math.Sin(s.Rot);
        for (int i = 0; i < ProfileSamples; i++)
        {
            double r = At(s.Radii, i, 1);
            double x = r * Cos[i], y = r * Sin[i];
            // rotation, then squash in screen space, then translation
            double rx = x * cr - y * sr;
            double ry = x * sr + y * cr;
            outPts[i] = new PointD((rx * s.Sx + s.Cx) * scale, (ry * s.Sy + s.Cy) * scale);
        }
        return outPts;
    }

    /// <summary>
    /// Closed polyline -> Catmull-Rom cubics (tension 1/6). Returns, for each point i, the two
    /// control points of the cubic going from point i to point i+1 (the original emits an SVG path).
    /// </summary>
    public static void ClosedPathControls(ReadOnlySpan<Vector2> pts, Span<Vector2> c1, Span<Vector2> c2, float tension = 1f / 6f)
    {
        int n = pts.Length;
        for (int i = 0; i < n; i++)
        {
            var p0 = pts[(i - 1 + n) % n];
            var p1 = pts[i];
            var p2 = pts[(i + 1) % n];
            var p3 = pts[(i + 2) % n];
            c1[i] = p1 + (p2 - p0) * tension;
            c2[i] = p2 - (p3 - p1) * tension;
        }
    }

    /// <summary>
    /// Arbitrary polygon -> radial profile, by ray casting from (cx, cy). Builds the shapes that are
    /// not naturally r(theta) (the conical bar of the "!"). Computed once at load, never per frame.
    /// </summary>
    public static double[] ProfileFromPolygon(IReadOnlyList<PointD> poly, double cx, double cy)
    {
        var radii = new double[ProfileSamples];
        int n = poly.Count;
        for (int k = 0; k < ProfileSamples; k++)
        {
            double dx = Cos[k], dy = Sin[k];
            double best = 0;
            for (int i = 0; i < n; i++)
            {
                var a = poly[i];
                var b = poly[(i + 1) % n];
                double ex = b.X - a.X, ey = b.Y - a.Y;
                double den = dx * ey - dy * ex;
                if (Math.Abs(den) < 1e-9) continue;
                double px = a.X - cx, py = a.Y - cy;
                double t = (px * ey - py * ex) / den; // distance along the ray
                double u = (px * dy - py * dx) / den; // position on the segment
                if (t > best && u >= 0 && u <= 1) best = t;
            }
            radii[k] = best;
        }
        return radii;
    }

    /// <summary>Convex hull of two circles: the conical bar of the upright "!".</summary>
    public static List<PointD> HullOfCircles(double x1, double y1, double r1, double x2, double y2, double r2, int steps = 96)
    {
        double dx = x2 - x1, dy = y2 - y1;
        double dist = Math.Sqrt(dx * dx + dy * dy);
        if (dist == 0) dist = 1e-6;
        // angle of the common external tangents
        double baseA = Math.Atan2(dy, dx);
        double spread = Math.Acos(Math.Max(-1, Math.Min(1, (r1 - r2) / dist)));
        var pts = new List<PointD>();
        // arc of the large circle
        for (int i = 0; i <= steps / 2; i++)
        {
            double a = baseA + spread + (Tau - 2 * spread) * i / (steps / 2);
            pts.Add(new PointD(x1 + Math.Cos(a) * r1, y1 + Math.Sin(a) * r1));
        }
        // arc of the small circle
        for (int i = 0; i <= steps / 2; i++)
        {
            double a = baseA - spread + 2 * spread * i / (steps / 2);
            pts.Add(new PointD(x2 + Math.Cos(a) * r2, y2 + Math.Sin(a) * r2));
        }
        return pts;
    }

    /// <summary>
    /// Profile radius in an arbitrary direction, interpolating the two neighbouring samples.
    /// Re-seats what sits "on" the body (eyes, notification pastille) when the silhouette is not
    /// a circle: otherwise an eye placed at 0.62 radius leaves a shape whose edge is at 0.55.
    /// </summary>
    public static double RadiusAtAngle(double[] radii, double angle)
    {
        int n = radii.Length;
        double t = ((angle / Tau % 1 + 1) % 1) * n;
        int i = (int)Math.Floor(t);
        return Lerp(At(radii, i % n, 1), At(radii, (i + 1) % n, 1), t - i);
    }

    /// <summary>Superellipse |x/sx|^n + |y/sy|^n = 1 (n = 2 ellipse, n ~ 4 squircle).</summary>
    public static double[] SuperellipseProfile(double n, double sx = 1, double sy = 1)
    {
        var o = new double[ProfileSamples];
        for (int i = 0; i < ProfileSamples; i++)
        {
            double c = Math.Pow(Math.Abs(Cos[i] / sx), n);
            double s = Math.Pow(Math.Abs(Sin[i] / sy), n);
            o[i] = Math.Pow(c + s, -1 / n);
        }
        return o;
    }

    /// <summary>
    /// Radial profile of a UNION of discs: r(theta) = farthest ray/circle intersection.
    /// Exact as long as the origin is inside the union (gives the cloud's bumps without path booleans).
    /// </summary>
    public static double[] UnionOfCirclesProfile(IEnumerable<(double x, double y, double r)> circles)
    {
        var list = circles.ToArray();
        var o = new double[ProfileSamples];
        for (int i = 0; i < ProfileSamples; i++)
        {
            double dx = Cos[i], dy = Sin[i];
            double best = 0;
            foreach (var c in list)
            {
                double b = dx * c.x + dy * c.y;
                double disc = b * b - (c.x * c.x + c.y * c.y - c.r * c.r);
                if (disc < 0) continue;
                double t = b + Math.Sqrt(disc);
                if (t > best) best = t;
            }
            o[i] = best;
        }
        return o;
    }

    /// <summary>
    /// Rounded-corner polygon via a Minkowski sum with a disc: each edge is pushed out by rc and
    /// each vertex becomes an arc of radius rc (so vertices go at the target radius MINUS rc).
    /// Expects a clockwise polygon in screen space (y down).
    /// </summary>
    static List<PointD> RoundedPolygon(PointD[] verts, double rc, int arcSteps = 10)
    {
        int n = verts.Length;
        var o = new List<PointD>();
        static double Normal(PointD a, PointD b)
        {
            double dx = b.X - a.X, dy = b.Y - a.Y;
            double len = Math.Sqrt(dx * dx + dy * dy);
            if (len == 0) len = 1;
            // clockwise + y down: the outward normal is (dy, -dx)
            return Math.Atan2(-dx / len, dy / len);
        }
        for (int i = 0; i < n; i++)
        {
            var prev = verts[(i - 1 + n) % n];
            var cur = verts[i];
            var next = verts[(i + 1) % n];
            double a0 = Normal(prev, cur), a1 = Normal(cur, next);
            double d = a1 - a0;
            while (d > Math.PI) d -= Tau;
            while (d < -Math.PI) d += Tau;
            for (int k = 0; k <= arcSteps; k++)
            {
                double a = a0 + d * k / arcSteps;
                o.Add(new PointD(cur.X + Math.Cos(a) * rc, cur.Y + Math.Sin(a) * rc));
            }
        }
        return o;
    }

    /// <summary>Regular polygon with rounded corners, inscribed in <paramref name="radius"/>.</summary>
    public static double[] RegularPolygonProfile(int sides, double radius, double rc, double rotationDeg = 0)
    {
        double rot = rotationDeg * Math.PI / 180;
        var verts = new PointD[sides];
        for (int i = 0; i < sides; i++)
        {
            // clockwise on screen: theta grows with y down
            double a = rot + (double)i / sides * Tau;
            verts[i] = new PointD(Math.Cos(a) * (radius - rc), Math.Sin(a) * (radius - rc));
        }
        return ProfileFromPolygon(RoundedPolygon(verts, rc), 0, 0);
    }
}
